### ISSUE TITLE
about recognition using tesseract

### ISSUE THREAD

**Issue by lerndeep** [sid0312/anpr_yolov5#3]
You mention you are using tesseract for recognition but in your repo I didn't find any code related to tesseract. could you please share tesseract code also?

**Comment by sid0312** [comment]
yeah about that, check my other repo https://github.com/sid0312/ANPR for the tesseract implementation

**Comment by leeyunhome** [comment]
Hello,

> yeah about that, check my other repo https://github.com/sid0312/ANPR for the tesseract implementation

Is there a reason not to use teserract in detect.py in sid0312/anpr_yolov5?

Thank you.

**Comment by leeyunhome** [comment]
> You mention you are using tesseract for recognition but in your repo I didn't find any code related to tesseract. could you please share tesseract code also?

Hello.
Was pytesseract used in anpr_yolov5?
If used, where can you check the code of anpr_yolov5?
If you look at the author's answer
It seems that https://github.com/sid0312/ANPR is using tesseract
I can't find it in the code of the anpr_yolov5 project.

Thank you.

**Comment by bharatsubedi** [comment]
I have implemented ALPR system using YOLOv5. check my repo for better understanding https://github.com/bharatsubedi/ALPR-Yolov5

**Comment by sid0312** [comment]
good work with the OCR
regards
