### ISSUE TITLE
plot_one_box, I think the order of the parameters has changed.

### ISSUE THREAD

**Issue by leeyunhome** [sid0312/anpr_yolov5#4]
Hello,

\anpr_yolov5\detect.py

on line101
plot_one_box(xyxy, im0, **label=label**, **color=colors[int(cls)]**, line_thickness=3)

\anpr_yolov5\utils\utils.py

on line906

def plot_one_box(x, img, **color=None**, **label=None**, line_thickness=None):

I think the order of the parameters has changed.
But there was no problem with the operation.
Was there no problem because there was a parameter default value?

Thank you.

**Comment by sid0312** [comment]
yes that's how python works!
